### ISSUE TITLE
No token on the request

### ISSUE THREAD

**Issue by caevv** [adrienkohlbecker/traefik-auth-cloudflare#2]
docker compose have the following config:

```
      - "traefik.backend=my"
      - "traefik.frontend.rule=Host:my.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=my.host"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=false"

      - "traefik.frontend.auth.forward.address=http://traefik-auth-cloudflare/auth/<audience>"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Auth-User"
```

Traefik version: 1.7
`traefik.toml`:
```
logLevel = "ERROR" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
InsecureSkipVerify = true
defaultEntryPoints = ["https", "http"]

# WEB interface of Traefik - it will show web page with overview of frontend and backend configurations
[api]
  entryPoint = "traefik"
  dashboard = true
  address = ":8080"

# Force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

[file]
  watch = true
  filename = "/etc/traefik/rules.toml"

# Let's encrypt configuration
[acme]
email = "<my-email>" #any email id will work
storage="/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging=true
onDemand = false #create certificate when container is created
[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 300
[[acme.domains]]
   main = "<my-domain>"
[[acme.domains]]
   main = "*.<my-domain>"

# Connection to docker host system (docker.sock)
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "<my-domain>"
watch = true
# This will hide all docker containers that don't have explicitly
# set label to "enable"
exposedbydefault = false
```

But I get `No token on the request`.

**Comment by seanturner83** [comment]
I've never made this work with 1.7. Works great with the ForwardAuth middleware in Traefik 2 though.

**Comment by caevv** [comment]
> I've never made this work with 1.7. Works great with the ForwardAuth middleware in Traefik 2 though.

Hey @seanturner83 do you have an example of your traefik.toml? Thanks.

**Comment by seanturner83** [comment]
We only use this with Kubernetes

**Comment by adrienkohlbecker** [comment]
Hey @caevv sorry about the delay. 

Did you manage to get it to work or is this still an issue? I'm interested to see your `docker-compose.yml` to understand how your containers are setup

**Comment by caevv** [comment]
Yes, I've used with Traefik 2 and it's working pretty good. 

I'm adding just the relevant bits here, let me know if you need more:


The only thing I have on my compose file is the entrypoints:

```yaml
    labels:
      - "traefik.http.routers.traefik.entrypoints=web,websecure"
```

traefik.yml
```yaml
entryPoints:
  websecure:
    address: :443
    http:
      middlewares:
        - myauth@file  # pointing to the auth middleware

providers:
  file:
    filename: /etc/traefik/dynamic_config.yml
```

dynamic_config.yml
```yaml
http:
  middlewares:
    myauth:
      forwardAuth:
        address: "http://traefik-auth-cloudflare/auth/{key}"
        authResponseHeaders:
          - "X-Auth-User"
```

If you want all in your docker compose, would be something like this (untested):
```yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=web,websecure"
      - "traefik.http.routers.whoami.rule=Host(`whoami.domain.tld`)"
      - "traefik.http.middlewares.myauth.forwardAuth.address="http://traefik-auth-cloudflare/auth/{key}"
      - "traefik.http.middlewares.myauth.forwardauth.authResponseHeaders=X-Auth-User"
```


_Btw I had to build myself a version for aarc64 to run on my ARM computer, I'd appreciate if you can do it in here :) https://www.docker.com/blog/multi-arch-images/_

**Comment by adrienkohlbecker** [comment]
That's great! I was just able to run the [built-in example](https://github.com/adrienkohlbecker/traefik-auth-cloudflare/tree/master/example) with 1.7, with minor updates to the docker-compose format, so I will close this issue and work on updating the example for traefik 2 (https://github.com/adrienkohlbecker/traefik-auth-cloudflare/issues/4).

I've also opened https://github.com/adrienkohlbecker/traefik-auth-cloudflare/issues/5 to track the multi-arch issue

**Comment by mudfyi** [comment]
> That's great! I was just able to run the [built-in example](https://github.com/adrienkohlbecker/traefik-auth-cloudflare/tree/master/example) with 1.7, with minor updates to the docker-compose format, so I will close this issue and work on updating the example for traefik 2 (#4).
> 
> I've also opened #5 to track the multi-arch issue

Any update on traefik2 examples?
