### ISSUE TITLE
Provide multi-arch image

### ISSUE THREAD

**Issue by adrienkohlbecker** [adrienkohlbecker/traefik-auth-cloudflare#5]
Requested by @caevv here: https://github.com/adrienkohlbecker/traefik-auth-cloudflare/issues/2#issuecomment-632731404

> Btw I had to build myself a version for aarc64 to run on my ARM computer, I'd appreciate if you can do it in here :) https://www.docker.com/blog/multi-arch-images/

**Comment by zhorvath83** [comment]
Do you plan to build amd64 arch (or multiarch) image for traefik-auth-cloudflare:2.0?

**Comment by adrienkohlbecker** [comment]
Hey @zhorvath83! Multi arch image is up, closing https://hub.docker.com/layers/akohlbecker/traefik-auth-cloudflare/2.0/images/sha256-8af0f27b65aa87e159e73a4f0e1102c3d0a2b6861f18e3888bfff04c40c70655?context=repo
